# conda env create --file environment.yml
name: menu-editor
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pyyaml
  - jupyterlab
  - fastapi
  - tinydb
  - invoke
  - uvicorn
  - jinja2
  - python-multipart